---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: GetIP
      infoblox:
        server: 13.70.140.114
        username: someone
        password: apassword
        api_version: 2.6
        action: reserve_next_available_ip
        network: "{{vlans}}"
        extattrs: "{{extattrs}}"
        comment: "{{the_comment}}"
      register: result

    - name: "Job result"
      debug: msg=" {{result}} "
